RPCClient: Add request URL as note on exception
For example:

```
>>> storage.revision_get(["rgrjgrjgoeigij"])
Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    storage.revision_get(["rgrjgrjgoeigij"])
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
[...]
swh.core.api.RemoteException: <RemoteException 500 UndefinedFunction: ['operator does not exist: text = sha1_git\nLINE 9:             LEFT JOIN revision ON t.id = revision.id\n                                               ^\nHINT:  No operator matches the given name and argument types. You might need to add explicit type casts.']>
Request: POST http://storage-postgresql-ro.internal.softwareheritage.org/revision
```